<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="49" failures="0" hostname="mycom" name="net.ion.framework.TestAllFramework" tests="97" time="927.782" timestamp="2011-09-10T04:50:57">
  <properties>
    <property name="java.vendor" value="Sun Microsystems Inc."></property>
    <property name="sun.java.launcher" value="SUN_STANDARD"></property>
    <property name="eclipse.pdebuild.templates" value="/D:/eclipse341/plugins/org.eclipse.pde.build_3.4.1.R34x_v20081217/templates/"></property>
    <property name="sun.management.compiler" value="HotSpot Client Compiler"></property>
    <property name="os.name" value="Windows XP"></property>
    <property name="sun.boot.class.path" value="D:\java\jdk5_22\jre\lib\rt.jar;D:\java\jdk5_22\jre\lib\i18n.jar;D:\java\jdk5_22\jre\lib\sunrsasign.jar;D:\java\jdk5_22\jre\lib\jsse.jar;D:\java\jdk5_22\jre\lib\jce.jar;D:\java\jdk5_22\jre\lib\charsets.jar;D:\java\jdk5_22\jre\classes"></property>
    <property name="TODAY" value="September 10 2011"></property>
    <property name="build.number" value="2"></property>
    <property name="sun.desktop" value="windows"></property>
    <property name="java.vm.specification.vendor" value="Sun Microsystems Inc."></property>
    <property name="ant.home" value="D:\eclipse341\plugins\org.apache.ant_1.7.0.v200803061910"></property>
    <property name="java.runtime.version" value="1.5.0_22-b03"></property>
    <property name="version.number" value="2"></property>
    <property name="user.name" value="Administrator"></property>
    <property name="ant.file.Jar Publish" value="D:\eclipse\workspace\ionframework\build.xml"></property>
    <property name="publishDir" value="./publish"></property>
    <property name="user.language" value="ko"></property>
    <property name="sun.boot.library.path" value="D:\java\jdk5_22\jre\bin"></property>
    <property name="manifest.main.class" value=""></property>
    <property name="ant.project.name" value="Jar Publish"></property>
    <property name="DSTAMP" value="20110910"></property>
    <property name="java.version" value="1.5.0_22"></property>
    <property name="user.timezone" value=""></property>
    <property name="sun.arch.data.model" value="32"></property>
    <property name="java.endorsed.dirs" value="D:\java\jdk5_22\jre\lib\endorsed"></property>
    <property name="sun.cpu.isalist" value="pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86"></property>
    <property name="sun.jnu.encoding" value="MS949"></property>
    <property name="file.encoding.pkg" value="sun.io"></property>
    <property name="file.separator" value="\"></property>
    <property name="java.specification.name" value="Java Platform API Specification"></property>
    <property name="java.class.version" value="49.0"></property>
    <property name="user.country" value="KR"></property>
    <property name="java.home" value="D:\java\jdk5_22\jre"></property>
    <property name="java.vm.info" value="mixed mode, sharing"></property>
    <property name="ant.file" value="D:\eclipse\workspace\ionframework\build.xml"></property>
    <property name="os.version" value="5.1"></property>
    <property name="test.reports" value="./resource/report"></property>
    <property name="path.separator" value=";"></property>
    <property name="java.vm.version" value="1.5.0_22-b03"></property>
    <property name="user.variant" value=""></property>
    <property name="ant.library.dir" value="D:\eclipse341\plugins\org.apache.ant_1.7.0.v200803061910\lib"></property>
    <property name="manifest.classpath" value="./"></property>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"></property>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"></property>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"></property>
    <property name="eclipse.pdebuild.scripts" value="/D:/eclipse341/plugins/org.eclipse.pde.build_3.4.1.R34x_v20081217/scripts/"></property>
    <property name="user.home" value="C:\Documents and Settings\Administrator"></property>
    <property name="java.specification.vendor" value="Sun Microsystems Inc."></property>
    <property name="binDir" value="./bin"></property>
    <property name="java.library.path" value="D:\java\jdk5_22\jre\bin;.;C:\WINDOWS\system32;C:\WINDOWS;D:/java/jdk5_22/bin/../jre/bin/client;D:/java/jdk5_22/bin/../jre/bin;D:\java\jdk5_22;D:\java\jdk5_22\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;D:\java\jdk5se_22\bin;D:\java\jdk5_22;D:\java\jdk5_22\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin"></property>
    <property name="java.vendor.url" value="http://java.sun.com/"></property>
    <property name="java.vm.vendor" value="Sun Microsystems Inc."></property>
    <property name="java.runtime.name" value="Java(TM) 2 Runtime Environment, Standard Edition"></property>
    <property name="java.class.path" value="D:\eclipse\workspace\ionframework\bin;D:\eclipse\workspace\ionframework\lib\ant.jar;D:\eclipse\workspace\ionframework\lib\common_apache_fat.jar;D:\eclipse\workspace\ionframework\lib\convert_fat.jar;D:\eclipse\workspace\ionframework\lib\jdbc_fat.jar;D:\eclipse\workspace\ionframework\lib\jetty_fat.jar;D:\eclipse\workspace\ionframework\lib\json_fat.jar;D:\eclipse\workspace\ionframework\lib\junit.jar;D:\eclipse\workspace\ionframework\lib\mail_fat.jar;D:\eclipse\workspace\ionframework\lib\pdf_fat.jar;D:\eclipse\workspace\ionframework\lib\rest_fat.jar;D:\eclipse\workspace\ionframework\lib\search_fat.jar;D:\eclipse\workspace\ionframework\lib\struts135_fat.jar;D:\eclipse\workspace\ionframework\lib\util_fat.jar;D:\eclipse\workspace\ionframework\lib\velocity_fat.jar;D:\eclipse\workspace\ionframework\lib\webservice_fat.jar;D:\eclipse\workspace\ionframework\lib\xml_fat.jar;D:\eclipse341\plugins\org.apache.ant_1.7.0.v200803061910\lib\ant-launcher.jar;D:\eclipse341\plugins\org.apache.ant_1.7.0.v200803061910\lib\ant.jar;D:\eclipse341\plugins\org.apache.ant_1.7.0.v200803061910\lib\ant-junit.jar"></property>
    <property name="ant.version" value="Apache Ant version 1.7.0 compiled on December 13 2006"></property>
    <property name="TSTAMP" value="0450"></property>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"></property>
    <property name="java.vm.specification.version" value="1.0"></property>
    <property name="sun.cpu.endian" value="little"></property>
    <property name="sun.os.patch.level" value="Service Pack 3"></property>
    <property name="eclipse.pdebuild.home" value="/D:/eclipse341/plugins/org.eclipse.pde.build_3.4.1.R34x_v20081217/./"></property>
    <property name="java.io.tmpdir" value="C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\"></property>
    <property name="java.vendor.url.bug" value="http://java.sun.com/cgi-bin/bugreport.cgi"></property>
    <property name="os.arch" value="x86"></property>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"></property>
    <property name="java.ext.dirs" value="D:\java\jdk5_22\jre\lib\ext"></property>
    <property name="user.dir" value="D:\eclipse\workspace\ionframework"></property>
    <property name="line.separator" value="
"></property>
    <property name="java.vm.name" value="Java HotSpot(TM) Client VM"></property>
    <property name="basedir" value="D:\eclipse\workspace\ionframework"></property>
    <property name="baseDir" value="."></property>
    <property name="ant.java.version" value="1.5"></property>
    <property name="TODAY_MY" value="09/10/2011 04:50"></property>
    <property name="ant.core.lib" value="D:\eclipse341\plugins\org.apache.ant_1.7.0.v200803061910\lib\ant.jar"></property>
    <property name="file.encoding" value="MS949"></property>
    <property name="java.specification.version" value="1.5"></property>
  </properties>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testInsensitive" time="0.25"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testEmpty" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testDocType" time="0.047"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testOnlyText" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testPrefix" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testContent" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testTagText" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testDepth" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testGetValue" time="0.0"></testcase>
  <testcase classname="net.ion.framework.parse.html.HTMLTest" name="testChild" time="0.016"></testcase>
  <testcase classname="net.ion.framework.parse.html.TestParser" name="testElementValue" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeCharSequenceTest" name="testRead" time="0.031">
    <error message=".\resource\data\AChristmasCarol.txt (지정된 경로를 찾을 수 없습니다)" type="java.io.FileNotFoundException">java.io.FileNotFoundException: .\resource\data\AChristmasCarol.txt (지정된 경로를 찾을 수 없습니다)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106)
	at java.io.FileReader.&lt;init&gt;(FileReader.java:55)
	at net.ion.framework.rope.RopeCharSequenceTest.stringBufferSpeed(RopeCharSequenceTest.java:54)
	at net.ion.framework.rope.RopeCharSequenceTest.testRead(RopeCharSequenceTest.java:33)
</error>
  </testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testEmpty" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testSubstringDeleteBug" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testRopeWriteBug" time="0.016"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testTemp" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testLengthOverflow" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testMatches" time="0.031"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testConcatenationFlatFlat" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testIterator" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testReverse" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testTrim" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testCreation" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testEquals" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testHashCode" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testHashCode2" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testIndexOf" time="0.016"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testInsert" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testPrepend" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testCompareTo" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testToString" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testReverseIterator" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testSerialize" time="0.031"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testPadStart" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testPadEnd" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testSubstringBounds" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testAppend" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testCharAt" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testRegexp" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testStartsEndsWith" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.RopeTest" name="testIndexOfBug" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeInputStream" name="testRead" time="0.015"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeInputStream" name="testCharAt" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeInputStream" name="testSpeed" time="0.0">
    <error message=".\resource\data\AChristmasCarol.txt (지정된 경로를 찾을 수 없습니다)" type="java.io.FileNotFoundException">java.io.FileNotFoundException: .\resource\data\AChristmasCarol.txt (지정된 경로를 찾을 수 없습니다)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:66)
	at net.ion.framework.rope.TestRopeInputStream.testSpeed(TestRopeInputStream.java:26)
</error>
  </testcase>
  <testcase classname="net.ion.framework.rope.TestRopeReader" name="testSpeed" time="0.0">
    <error message=".\resource\data\Autobiography.txt (지정된 경로를 찾을 수 없습니다)" type="java.io.FileNotFoundException">java.io.FileNotFoundException: .\resource\data\Autobiography.txt (지정된 경로를 찾을 수 없습니다)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:66)
	at net.ion.framework.rope.TestRopeReader.testSpeed(TestRopeReader.java:33)
</error>
  </testcase>
  <testcase classname="net.ion.framework.rope.TestRopeReader" name="testReader" time="0.016"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeReader" name="testSpeedDiff" time="0.0">
    <error message=".\resource\data\Autobiography.txt (지정된 경로를 찾을 수 없습니다)" type="java.io.FileNotFoundException">java.io.FileNotFoundException: .\resource\data\Autobiography.txt (지정된 경로를 찾을 수 없습니다)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:66)
	at net.ion.framework.rope.TestRopeReader.testSpeedDiff(TestRopeReader.java:50)
</error>
  </testcase>
  <testcase classname="net.ion.framework.rope.TestRopeReader" name="testBuildReader" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeReader" name="testNull" time="0.0"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeWriter" name="testWriterSpped" time="0.031"></testcase>
  <testcase classname="net.ion.framework.rope.TestRopeWriter" name="testRopeWriterSpped" time="0.141"></testcase>
  <testcase classname="net.ion.framework.db.sample.dc.DCInit" name="testDCInit" time="0.406">
    <error message="IO 예외 상황: Connection reset by peer: socket write error" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: Connection reset by peer: socket write error
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.dc.DCInit" name="testServant" time="21.047">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.dc.DCInit" name="testServantChain" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.dc.ConnectionLess" name="testThread" time="21.031">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P1_SelectQuery" name="testDefault" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P1_SelectQuery" name="testGetRows" time="21.031">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P1_SelectQuery" name="testParameter" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P1_SelectQuery" name="testFirstRow" time="21.032">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P2_UpdateQuery" name="testParameter" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P2_UpdateQuery.setUp(P2_UpdateQuery.java:9)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P2_UpdateQuery" name="testFirst" time="20.922">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P2_UpdateQuery.setUp(P2_UpdateQuery.java:9)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P3_BatchCommandQuery" name="testBatchDefault" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P3_BatchCommandQuery.setUp(P3_BatchCommandQuery.java:13)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P3_BatchCommandQuery" name="testAddParamCase1" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P3_BatchCommandQuery.setUp(P3_BatchCommandQuery.java:13)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P3_BatchCommandQuery" name="testAddParamCase2" time="21.031">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P3_BatchCommandQuery.setUp(P3_BatchCommandQuery.java:13)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P3_BatchCommandQuery" name="testAddParamCase3" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P3_BatchCommandQuery.setUp(P3_BatchCommandQuery.java:13)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P3_BatchCommandQuery" name="testTransaction" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P3_BatchCommandQuery.setUp(P3_BatchCommandQuery.java:13)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P4_UserProcedure" name="testProcedureUpdate" time="21.218">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P4_UserProcedure.setUp(P4_UserProcedure.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P4_UserProcedure" name="testProcedureQuery" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P4_UserProcedure.setUp(P4_UserProcedure.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P5_UserProceduresQuery" name="testUpdate" time="20.922">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P5_UserProceduresQuery.setUp(P5_UserProceduresQuery.java:14)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P5_UserProceduresQuery" name="testMultiQuery" time="21.032">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P5_UserProceduresQuery.setUp(P5_UserProceduresQuery.java:14)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P6_UserProceduresUpdate" name="testUserProcedures" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P6_UserProceduresUpdate.setUp(P6_UserProceduresUpdate.java:14)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.first.P6_UserProceduresUpdate" name="testSimpleTransaction" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.first.P6_UserProceduresUpdate.setUp(P6_UserProceduresUpdate.java:14)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.CombinedQuery" name="testFirst" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.CombinedQuery.setUp(CombinedQuery.java:14)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.CombinedQuery" name="testSecond" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.CombinedQuery.setUp(CombinedQuery.java:14)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.LobHandle" name="testInsert" time="21.234">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.LobHandle.setUp(LobHandle.java:23)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.LobHandle" name="testParam" time="21.11">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.LobHandle.setUp(LobHandle.java:23)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.TestNamedParameter" name="testNamedParameter" time="21.031">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.TestNamedParameter.setUp(TestNamedParameter.java:17)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.TestNamedParameter" name="testNamedParameterDupl" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.TestNamedParameter.setUp(TestNamedParameter.java:17)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.TestNamedParameter" name="testNamedProcedure" time="21.032">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.TestNamedParameter.setUp(TestNamedParameter.java:17)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.TestNamedParameter" name="testBatch" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.TestNamedParameter.setUp(TestNamedParameter.java:17)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.TestNamedParameter" name="testNamedBatch" time="21.032">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
	at net.ion.framework.db.sample.extend.TestNamedParameter.setUp(TestNamedParameter.java:17)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.QueryPage" name="testRowsPage" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.extend.QueryPage" name="testRowsPageMethod2" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.handler.UseHandler" name="testMapHandler" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.handler.UseHandler" name="testMapList" time="21.031">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.handler.UseHandler" name="testBeanList" time="21.016">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.handler.UseHandler" name="testScalar" time="20.922">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.plan.ViewPlan" name="testViewPlan" time="21.031">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsFirstRow" name="testFirstRow" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsGet" name="testDate" time="21.032">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsGet" name="testSetClob" time="21.015">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsGet" name="testGetClob0" time="20.922">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsGet" name="testGetClob" time="21.219">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsPage" name="testDefaultLimit" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsPage" name="testNextPage" time="21.125">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.rows.RowsPage" name="testPrePage" time="20.922">
    <error message="IO 예외 상황: The Network Adapter could not establish the connection" type="java.sql.SQLException">java.sql.SQLException: IO 예외 상황: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:439)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at net.ion.framework.db.manager.OracleDBManager.getConnection(OracleDBManager.java:46)
	at net.ion.framework.db.procedure.AbstractQueryable.getConnection(AbstractQueryable.java:185)
	at net.ion.framework.db.procedure.AbstractQueryable.execQuery(AbstractQueryable.java:111)
	at net.ion.framework.db.manager.OracleDBManager.heartbeatQuery(OracleDBManager.java:79)
	at net.ion.framework.db.manager.DBManager.initPool(DBManager.java:74)
	at net.ion.framework.db.DBController.initSelf(DBController.java:221)
	at net.ion.framework.db.DBController.initSelf(DBController.java:214)
	at net.ion.framework.db.sample.TestBaseDB.setUp(TestBaseDB.java:25)
</error>
  </testcase>
  <testcase classname="net.ion.framework.db.sample.servant.TestServant" name="testInit" time="0.422"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[2011. 9. 10 오전 4:50:58 net.ion.framework.db.servant.ServantChannel <init>
정보: init Channel : Thread-0(class net.ion.framework.db.servant.StdOutServant)
]]></system-err>
</testsuite>
